version: '3'
services:
  db:
    image: mysql:8.0
    container_name: forum_db
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: redis:latest
    container_name: redis_local
    restart: unless-stopped
    ports:
      - '6379:6379'