spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/forum
    username: gustavo
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true